/** Docusaurus 侧边栏 · 自动从 docs/chapters/* 抓取 */
const sidebars = {
  main: [
    {
      type: 'category',
      label: '⭐ 接入模式',
      link: { type: 'doc', id: '00-adoption/README' },
      items: [
        '00-adoption/mode-a-greenfield',
        '00-adoption/mode-b-mid-dev',
        '00-adoption/mode-c-iterating',
        '00-adoption/mode-d-maintenance',
      ],
    },
    {
      type: 'category',
      label: '01 总览',
      link: { type: 'doc', id: '01-overview/README' },
      items: [{ type: 'autogenerated', dirName: '01-overview' }],
    },
    {
      type: 'category',
      label: '02 业务篇',
      link: { type: 'doc', id: '02-business/README' },
      items: [{ type: 'autogenerated', dirName: '02-business' }],
    },
    {
      type: 'category',
      label: '03 开发篇',
      link: { type: 'doc', id: '03-development/README' },
      items: [{ type: 'autogenerated', dirName: '03-development' }],
    },
    {
      type: 'category',
      label: '04 测试篇',
      link: { type: 'doc', id: '04-testing/README' },
      items: [{ type: 'autogenerated', dirName: '04-testing' }],
    },
    {
      type: 'category',
      label: '05 运维篇',
      link: { type: 'doc', id: '05-operations/README' },
      items: [{ type: 'autogenerated', dirName: '05-operations' }],
    },
  ],
};

export default sidebars;
