/** Docusaurus 侧边栏 · 自动从 docs/chapters/* 抓取
 *
 * 注意: Docusaurus 会自动剥离目录 / 文件名的数字前缀,所以:
 *   00-adoption/     → adoption/
 *   01-prd-standards → prd-standards
 */
const sidebars = {
  main: [
    {
      type: 'category',
      label: '⭐ 接入模式',
      link: { type: 'doc', id: 'adoption/README' },
      items: [
        'adoption/mode-a-greenfield',
        'adoption/mode-b-mid-dev',
        'adoption/mode-c-iterating',
        'adoption/mode-d-maintenance',
      ],
    },
    {
      type: 'category',
      label: '01 总览',
      link: { type: 'doc', id: 'overview/README' },
      items: [{ type: 'autogenerated', dirName: '01-overview' }],
    },
    {
      type: 'category',
      label: '02 业务篇',
      link: { type: 'doc', id: 'business/README' },
      items: [{ type: 'autogenerated', dirName: '02-business' }],
    },
    {
      type: 'category',
      label: '03 开发篇',
      link: { type: 'doc', id: 'development/README' },
      items: [{ type: 'autogenerated', dirName: '03-development' }],
    },
    {
      type: 'category',
      label: '04 测试篇',
      link: { type: 'doc', id: 'testing/README' },
      items: [{ type: 'autogenerated', dirName: '04-testing' }],
    },
    {
      type: 'category',
      label: '05 运维篇',
      link: { type: 'doc', id: 'operations/README' },
      items: [{ type: 'autogenerated', dirName: '05-operations' }],
    },
  ],
};

export default sidebars;
